- name: Play 1 - Run Roles for miscellaneous softwares,Apache & Tomcat
  hosts: webservers
  become: yes
  vars:
    v_role_path: "roles"
  roles:
    - "{{ v_role_path }}/miscellaneous"
    - "{{ v_role_path }}/apache"
    - "{{ v_role_path }}/tomcat"

- name: Play 3 - Python Install
  hosts: webservers
  become: yes
  tasks:
    - name: Install Python 3.9
      yum:
        name: python
        state: present
      tags: python-install
    - name: pip module installation
      yum:
        name: python3-pip
        state: present
      tags: python3 pip

- name: Play 4 - Python library install and copying of War file
  hosts: webservers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Install boto3 and botocore with pip3 module
      pip:
        name:
          - boto
          - boto3
          - botocore
        executable: pip
      tags: boto-lib-install
  




